name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: echo NODE_VERSION=$(jq -r .volta.node package.json) >> $GITHUB_ENV
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org/'
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - run: npm ci

      - run: npm version "${{ github.event.release.tag_name }}" --no-git-tag-version

      
      - run:  npm publish --access public
        if: "!github.event.release.prerelease"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: npm publish --access public --tag next
        if: "github.event.release.prerelease"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
