name: Test

on: 
  push:
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - LICENSE
      - .gitignore
      - .npmignore


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run citest
